
nameOverride: ""
fullnameOverride: ""

argo:
  namespace: argocd

projects:
  platform-services:
    description: Shared platform services
    sourceRepos:
      - '*'
    destinations:
      - namespace: platform
        server: https://kubernetes.default.svc
      - namespace: cert-manager
        server: https://kubernetes.default.svc
      - namespace: monitoring
        server: https://kubernetes.default.svc
      - namespace: argocd
        server: https://kubernetes.default.svc
      - namespace: kube-system
        server: https://kubernetes.default.svc
      - namespace: longhorn-system
        server: https://kubernetes.default.svc
    clusterResourceWhitelist:
      - group: '*'
        kind: '*'
    clusterResourceBlacklist: false
    namespaceResourceWhitelist:
      - group: '*'
        kind: '*'
    namespaceResourceBlacklist: false
    roles: []
  user-services:
    description: Project for user deployed services
    sourceRepos:
      - '*'
    destinations:
      - namespace: '*'
        server: '*'
    clusterResourceWhitelist:
      - group: '*'
        kind: '*'
    clusterResourceBlacklist: false
    namespaceResourceWhitelist:
      - group: '*'
        kind: '*'
    namespaceResourceBlacklist: false
    roles: []

application_defaults:
  source:
    targetRevision: HEAD
    path: '.'
  destination:
    server: https://kubernetes.default.svc
  syncPolicy:
    automated:
      prune: false
      selfHeal: true
      allowEmpty: false
    syncOptions:
      - Validate=true
      - CreateNamespace=true
      - PrunePropagationPolicy=foreground
      - PruneLast=true
  values: {}

applications:
  cert-manager:
    project: platform-services
    source:
      repoUrl: https://github.com/tmacro/cloud-charts.git
      path: 'charts/cert-manager'
      targetRevision: cert-manager-0.1.0
    destination:
      namespace: cert-manager
    values: {}
  authentication:
    project: platform-services
    source:
      repoUrl: https://github.com/tmacro/cloud-charts.git
      path: 'charts/sso'
      targetRevision: sso-0.3.4
    destination:
      namespace: platform
    values: {}
  nfs-provisioner:
    project: platform-services
    source:
      repoUrl: https://github.com/tmacro/cloud-charts.git
      path: 'charts/nfs-provisioner'
      targetRevision: nfs-provisioner-0.1.0
    destination:
      namespace: platform
    values: {}
  traefik-dashboard:
    project: platform-services
    source:
      repoUrl: https://github.com/tmacro/cloud-charts.git
      path: 'charts/traefik-dashboard'
      targetRevision: traefik-dashboard-0.2.0
    destination:
      namespace: kube-system
    values: {}
  lock-operator-crds:
    project: platform-services
    source:
      repoUrl: https://git.sr.ht/~tmacro/dlm
      path: 'manifests/crd/'
      targetRevision: HEAD
    destination:
      namespace: platform
  lock-operator:
    project: platform-services
    source:
      repoUrl: https://github.com/tmacro/cloud-charts.git
      path: 'charts/dlm'
      targetRevision: HEAD
    values:
      clusterlocks:
        - unattended-upgrades
    destination:
      namespace: platform
  longhorn:
    project: platform-services
    source:
      repoUrl: https://github.com/tmacro/cloud-charts.git
      path: charts/longhorn
      targetRevision: HEAD
    destination:
      namespace: longhorn-system
    values: {}

namespaces:
  platform:
    labels:
      cert-manager-tls: service
  workload:
    labels:
      cert-manager-tls: service
