---
apiVersion: v1
kind: Secret
metadata:
  name: authelia-service-credentials
  labels:
    app.kubernetes.io/name: authelia
    {{- include "sso.helmLabels" . | nindent 4 }}
type: Opaque
stringData:
  postgresql-password: {{ .Values.authelia.credentials.postgresqlPassword | quote }}
  postgresql-postgres-password: {{ .Values.authelia.credentials.postgresqlAdminPassword | quote }}
  JWT_TOKEN: {{ .Values.authelia.session.jwtToken | quote }}
  SESSION_ENCRYPTION_KEY: {{ .Values.authelia.session.sessionEncryptionKey | quote }}
  OIDC_PRIVATE_KEY: {{ .Values.authelia.configMap.identity_providers.oidc.oidcPrivateKey | quote }}
  OIDC_HMAC_SECRET: {{ .Values.authelia.configMap.identity_providers.oidc.oidcHmacSecret | quote }}
  SMTP_PASSWORD: {{ .Values.authelia.smtp_password | quote }}
