---
apiVersion: v1
kind: Secret
metadata:
  name: authelia-service-credentials
  labels:
    app.kubernetes.io/name: authelia
    argocd.argoproj.io/sync-options: Prune=false
    argocd.argoproj.io/compare-options: IgnoreExtraneous
    {{- include "sso.helmLabels" . | nindent 4 }}
type: Opaque
data:
  {{- $secret := (lookup "v1" "Secret" .Release.Namespace "authelia-service-credentials") | default (dict) -}}
  {{- $secretData := (get $secret "data") | default (dict) -}}
  {{- $password := (get $secretData "postgresql-password") | default (randAlphaNum 32 | b64enc) }}
  {{- $adminPassword := (get $secretData "postgresql-postgres-password") | default (randAlphaNum 32 | b64enc) }}
  {{- $jwtToken := (get $secretData "JWT_TOKEN") | default (randAlphaNum 32 | b64enc) }}
  {{- $sessionToken := (get $secretData "SESSION_ENCRYPTION_KEY") | default (randAlphaNum 32 | b64enc) }}
  {{- $oidcKey := (get $secretData "OIDC_PRIVATE_KEY") | default (genPrivateKey "rsa" | b64enc) }}
  {{- $oidcHmac := (get $secretData "OIDC_HMAC_SECRET") | default (randAlphaNum 32 | b64enc) }}
  postgresql-password: {{ $password | quote }}
  postgresql-postgres-password: {{ $adminPassword | quote }}
  JWT_TOKEN: {{ $jwtToken | quote }}
  SESSION_ENCRYPTION_KEY: {{ $sessionToken | quote }}
  OIDC_PRIVATE_KEY: {{ $oidcKey | quote }}
  OIDC_HMAC_SECRET: {{ $oidcHmac | quote }}
  SMTP_PASSWORD: {{ .Values.authelia.smtp_password | b64enc | quote }}
