---
apiVersion: helm.cattle.io/v1
kind: HelmChartConfig
metadata:
  name: traefik
  namespace: kube-system
  labels:
    {{- include "sso.helmLabels" . | nindent 4 }}
spec:
  valuesContent: |-
    providers:
      kubernetesCRD:
        allowCrossNamespace: True
    ports:
      web:
        port: 80
      websecure:
        port: 443
    additionalArguments:
      - --entrypoints.web.http.redirections.entryPoint.to=websecure
      - --entrypoints.websecure.http.middlewares=platform-chain-authelia-auth@kubernetescrd
    {{- if gt (len (default (list) .Values.traefik.additionalArgs)) 0 }}
      {{- .Values.traefik.additionalArgs | toYaml | nindent 6 }}
    {{- end }}
