---
apiVersion: v1
kind: Secret
metadata:
  name: authelia-user-database
  labels:
    app.kubernetes.io/name: authelia
    {{- include "sso.helmLabels" . | nindent 4 }}
type: Opaque
data:
  users_database: {{ include "sso.autheliaSecretUserDB" . | b64enc | quote }}
