{{- with $defaults := .Values.application_defaults }}
{{- range $name, $app := $.Values.applications }}
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: {{ $name }}
  namespace: {{ $.Values.argo.namespace }}
  labels:
    {{- include "platform.helmLabels" $ | nindent 4 }}
spec:
  project: '{{ $app.project }}'
  source:
    repoURL: '{{ $app.source.repoUrl }}'
    targetRevision: {{ $app.source.targetRevision | default $defaults.source.targetRevision }}
    path: '{{ $app.source.path | default $defaults.source.path }}'
    {{- if hasKey $app "values" }}
    helm:
      values: |
        {{- $app.values | default $defaults.values | toYaml | nindent 8 }}
    {{- end }}
  destination:
    server: {{ $app.destination.server | default $defaults.destination.server }}
    namespace: {{ $app.destination.namespace }}
  {{- with $sP := $app.syncPolicy | default $defaults.syncPolicy }}
  syncPolicy:
    {{- with $auto := $sP.automated | default $defaults.syncPolicy.automated }}
    automated: # automated sync by default retries failed attempts 5 times with following delays between attempts ( 5s, 10s, 20s, 40s, 80s ); retry controlled using `retry` field.
      prune: {{ $auto.prune }} # Specifies if resources should be pruned during auto-syncing ( false by default ).
      selfHeal: {{ $auto.selfHeal }} # Specifies if partial app sync should be executed when resources are changed only in target Kubernetes cluster and no git change detected ( false by default ).
      allowEmpty: {{ $auto.allowEmpty }} # Allows deleting all application resources during automatic syncing ( false by default ).
    {{- end }}
    {{- if ne (len (default $defaults.syncOptions $sP.syncOptions)) 0 }}
    syncOptions:
      {{- $sP.syncOptions | default $defaults.syncOptions | toYaml | nindent 6 }}
    {{- else }}
    syncOptions: []
    {{- end }}
  {{- end }}
{{- end }}
{{- end }}
