---
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: lets-encrypt-issuer
  labels:
    app.kubernetes.io/name: {{ include "cert-manager.name" . }}
    {{- include "cert-manager.helmLabels" . | nindent 4 }}
  annotations:
    "helm.sh/hook": post-install
    "helm.sh/hook-weight": "99"
spec:
  acme:
    email: {{ .Values.dns.cloudflare_email }}
    {{- if .Values.dns.staging }}
    server: https://acme-staging-v02.api.letsencrypt.org/directory
    {{- else }}
    server: https://acme-v02.api.letsencrypt.org/directory
    {{- end }}
    privateKeySecretRef:
      name: cluster-issuer-account-key
    solvers:
    - dns01:
        cloudflare:
          email: {{ .Values.dns.cloudflare_email }}
          apiTokenSecretRef:
            name: cloudflare-api-token-secret
            key: api-token
