---
apiVersion: v1
kind: Secret
metadata:
  name: cloudflare-api-token-secret
  labels:
    app.kubernetes.io/name: {{ include "cert-manager.name" . }}
    {{- include "cert-manager.helmLabels" . | nindent 4 }}
type: Opaque
stringData:
  api-token: {{ .Values.dns.cloudflare_token | quote}}
