apiVersion: v2
name: cert-manager
description: A Helm chart for Kubernetes
type: application
version: '1.0.0'
appVersion: '1.0.0'
dependencies:
  - name: cert-manager
    version: 1.6.1
    repository: https://charts.jetstack.io
  - name: kubed
    version: 0.12.0
    condition: kubed.enabled
    repository: https://charts.appscode.com/stable/
