apiVersion: v2
name: sso
description: Install the SSO stack used by tmacs.cloud.
type: application
version: '0.3.7'
appVersion: "1.0.0"
dependencies:
  - name: postgresql
    version: 10.13.8
    repository: https://charts.bitnami.com/bitnami
    condition: authelia-postgres.enabled
    alias: authelia-postgres

  - name: redis
    version: 15.5.5
    repository: https://charts.bitnami.com/bitnami
    condition: authelia-redis.enabled
    alias: authelia-redis

  - name: authelia
    version: 0.6.3
    repository: https://charts.authelia.com
    condition: authelia.enabled
    alias: authelia
