{{ with $root := . }}
{{ range $secret, $conf := .Values.secrets | default (dict) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "cloud-deploy.fullname" $root }}-{{ $secret }}
  namespace: {{ $conf.namespace }}
  labels:
    {{- include "cloud-deploy.labels" . | nindent 4 }}
type: {{ $conf.type }}
data: {{ $conf.data }}
{{- end }}
{{- end }}
