---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "cloud-deploy.fullname" . }}
  labels:
    {{- include "cloud-deploy.labels" . | nindent 4 }}
spec:
  clusterIP: None
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "cloud-deploy.selectorLabels" . | nindent 4 }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "cloud-deploy.fullname" . }}-ui
  labels:
    {{- include "cloud-deploy.labels" . | nindent 4 }}
spec:
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http-deploy-ui
      protocol: TCP
      name: http
  selector:
    {{- include "cloud-deploy.selectorLabels" . | nindent 4 }}
