apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ include "cloud-deploy.fullname" . }}
  labels:
    {{- include "cloud-deploy.labels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      {{- include "cloud-deploy.selectorLabels" . | nindent 6 }}
  serviceName: {{ include "cloud-deploy.fullname" . }}
  replicas: 1
  template:
    metadata:
      labels:
        {{- include "cloud-deploy.labels" . | nindent 8 }}
    spec:
      terminationGracePeriodSeconds: 120
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
        - name: {{ .Chart.Name }}
          {{- if .Values.securityContext }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 10 }}
          {{- end }}
          image: "{{ .Values.image.deploy.repository }}:{{ .Values.image.deploy.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.deploy.pullPolicy }}
          ports:
            - name: http-deploy-api
              containerPort: 9000
              protocol: TCP
          env:
            - name: CLOUDCONF_VERSION
              value: {{ .Values.cloudconf_version }}
            - name: ALLOW_TERRAFORM_DELETES
              valueFrom:
                configMapKeyRef:
                  name: env-deploy-config
                  key: enableTerraformDeletes
                  optional: True
            - name: ENABLE_DEPLOY_JOB
              valueFrom:
                configMapKeyRef:
                  name: env-deploy-config
                  key: enableDeployJob
                  optional: True
          livenessProbe:
            httpGet:
              path: /
              port: http
          readinessProbe:
            httpGet:
              path: /
              port: http
          {{- if .Values.resources.deploy }}
          resources:
            {{- toYaml .Values.resources.deploy | nindent 10 }}
          {{- end }}
          volumeMounts:
            - name: inventory-secret
              mountPath: /var/lib/cloud-deploy/inventory
              subPath: inventory
              readOnly: True
            - name: deploy-secret
              mountPath: /var/lib/cloud-deploy/ssh_key
              subPath: deploy_key
              readOnly: True
            - name: config-secret
              mountPath: /var/lib/cloud-deploy/gpg_key
              subPath: gpg_key
              readOnly: True
        - name: {{ .Chart.Name }}-ui
          {{- if .Values.securityContext }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 10 }}
          {{- end }}
          image: "{{ .Values.image.ui.repository }}:{{ .Values.image.ui.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.ui.pullPolicy }}
          ports:
            - name: http-deploy-ui
              containerPort: 80
              protocol: TCP
          env:
            - name: CLOUDCONF_VERSION
              value: {{ .Values.cloudconf_version }}
            - name: CLOUD_DEPLOY_VERSION
              value: {{ .Values.image.deploy.tag}}
          livenessProbe:
            httpGet:
              path: /
              port: http
          readinessProbe:
            httpGet:
              path: /
              port: http
          {{- if .Values.resources.ui }}
          resources:
            {{- toYaml .Values.resources.ui | nindent 10 }}
          {{- end }}
      volumes:
        - name: inventory-secret
          secret:
            secretName: {{ .Values.existingSecrets.inventory }}
            defaultMode: 256
        - name: deploy-secret
          secret:
            secretName: {{ .Values.existingSecrets.deploy_key }}
            defaultMode: 256
        - name: config-secret
          secret:
            secretName: {{ .Values.existingSecrets.cloudconf }}
            defaultMode: 256
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
