name: Release Charts

on:
  push:
    branches:
      - trunk
      
jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Configure Git
        run: |
          git config user.name "$GITHUB_ACTOR"
          git config user.email "$GITHUB_ACTOR@users.noreply.github.com"

      - name: Install Helm
        uses: azure/setup-helm@v1
        with:
          version: v3.7.1
      
      - name: Add upstream repos
        run: |
          helm repo add jetstack https://charts.jetstack.io
          helm repo add appscode https://charts.appscode.com/stable/
          helm repo add authelia https://charts.authelia.com
          helm repo add nfs-provisioner https://kubernetes-sigs.github.io/nfs-subdir-external-provisioner/
          helm repo add bitnami https://charts.bitnami.com/bitnami
          
      - name: Run chart-releaser
        uses: helm/chart-releaser-action@v1.3.0
        with:
          charts_repo_url: charts.tmacro.dev
        env:
          CR_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
